import type { RuleListItem, CategoryOption } from './types';

export const MOCK_CATEGORIES: CategoryOption[] = [
  { id: 'cat-001', code: 'REV-01', name: 'Doanh thu bán hàng' },
  { id: 'cat-002', code: 'REV-02', name: 'Tiền chuyển khoản cá nhân' },
  { id: 'cat-003', code: 'REV-03', name: 'Doanh thu dịch vụ' },
  { id: 'cat-004', code: 'REV-04', name: 'Giao dịch nhỏ lẻ' },
  { id: 'cat-005', code: 'EXP-01', name: 'Chi phí vận hành' },
  { id: 'cat-006', code: 'EXP-02', name: 'Chi phí nhân sự' },
  { id: 'cat-007', code: 'REV-05', name: 'Doanh thu TMĐT (Shopee/Lazada)' },
  { id: 'cat-008', code: 'OTHER', name: 'Khác / Chưa xác định' },
];

export const MOCK_RULES: RuleListItem[] = [
  {
    id: 'rule-001',
    category_id: 'cat-001',
    category_code: 'REV-01',
    category_name: 'Doanh thu bán hàng',
    keyword: 'thanh\\s+toan.*don\\s+hang',
    type: 'regex',
    priority: 5,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 89,
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 'rule-002',
    category_id: 'cat-002',
    category_code: 'REV-02',
    category_name: 'Tiền chuyển khoản cá nhân',
    keyword: 'chuyen tien|chuyen khoan|ck nhan',
    type: 'keyword',
    priority: 10,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: false,
    is_active: true,
    match_count: 156,
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 'rule-003',
    category_id: 'cat-007',
    category_code: 'REV-05',
    category_name: 'Doanh thu TMĐT (Shopee/Lazada)',
    keyword: 'shopee|lazada|tiki',
    type: 'composite',
    priority: 8,
    amount_min: 100000,
    amount_max: 50000000,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 55,
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-03-05T00:00:00Z',
  },
  {
    id: 'rule-004',
    category_id: 'cat-004',
    category_code: 'REV-04',
    category_name: 'Giao dịch nhỏ lẻ',
    keyword: '',
    type: 'amount',
    priority: 50,
    amount_min: 0,
    amount_max: 50000,
    conditions: null,
    stop_on_match: false,
    is_active: true,
    match_count: 45,
    created_at: '2026-02-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'rule-005',
    category_id: 'cat-005',
    category_code: 'EXP-01',
    category_name: 'Chi phí vận hành',
    keyword: 'tien dien|tien nuoc|tien internet|phi dich vu',
    type: 'keyword',
    priority: 12,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: false,
    is_active: true,
    match_count: 30,
    created_at: '2026-02-20T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'rule-006',
    category_id: 'cat-006',
    category_code: 'EXP-02',
    category_name: 'Chi phí nhân sự',
    keyword: 'luong|tien luong|luong thang',
    type: 'keyword',
    priority: 15,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: false,
    is_active: true,
    match_count: 20,
    created_at: '2026-02-20T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'rule-007',
    category_id: 'cat-003',
    category_code: 'REV-03',
    category_name: 'Doanh thu dịch vụ',
    keyword: 'hoa don dich vu|phi dich vu|thanh toan dv',
    type: 'exact',
    priority: 3,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: false,
    match_count: 12,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'rule-008',
    category_id: 'cat-008',
    category_code: 'OTHER',
    category_name: 'Khác / Chưa xác định',
    keyword: '',
    type: 'fallback',
    priority: 999,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: false,
    is_active: true,
    match_count: 28,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];
